language: node_js
node_js:
  - 0.10

before_install:
# We need this line to have g++4.8 available in apt
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8
# We want to compile with g++ 4.8 when rather than the default g++
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

script:
  - git clone https://github.com/nfroidure/woff2.git
  - cd woff2
  - git submodule init
  - git submodule update
  - make clean all
  - cd ..
  - env PATH=$PATH:$(dirname $0)/woff2 npm test
